version: '3'

services:
  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@2020
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  app:
    container_name: study-repetition-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    environment:
      DB_HOST: postgres
    ports:
      - '3000:3000'
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

volumes:
  db-volume:
